Skip build if its `id` is already in Build table.
gradle/ge-export pull request #13
Opened 2017-07-05 22:32 UTC by wisechengyi

Other minor changes:
* Upgrade gradle to 4.0
* Add `-Ddebug` feature to allow remote debug
* Some formatting

2017-07-05 23:00 UTC, w25r requested changes
One minor change I'd like you to make and I also need to try it out.  I will do that tomorrow.  Looks good!

Thanks!

2017-07-05 23:00 UTC, w25r commented on build.gradle
> +    if (System.getProperty('debug') != null) {
This is fine for now, but we'll want to make this a project property rather than a system property eventually.

2017-07-05 23:00 UTC, w25r commented on src/main/java/com/gradle/exportapi/EventProcessor.java
> +            log.warn(String.format("Skipped build %s that is already in db. This could entail an incomplete export from previous run.",
No reason to use String.format

```java
log.warn("Skipping build {} as it is already in the database.", currentBuild.getBuildId());
```
Also, remove the warning about an incomplete export.  That's not relevant here.

2017-07-06 00:13 UTC, wisechengyi commented on src/main/java/com/gradle/exportapi/EventProcessor.java
> +            log.warn(String.format("Skipped build %s that is already in db. This could entail an incomplete export from previous run.",
corrected. thanks

2017-07-06 01:16 UTC, KidDaedalus commented
I like it. Thanks for saving me the trouble of doing this! 👍

2017-07-06 22:00 UTC, w25r approved these changes

2017-07-06 22:00 UTC, merged